name: Build Hugo Site

# Το action ενεργοποιείται κάθε φορά που γίνεται push στον main κλάδο
on:
    push:
        branches:
            - main # Εδώ μπορείς να αλλάξεις τον κλάδο αν είναι άλλος εκτός από τον "main"

jobs:
    build:
        runs-on: ubuntu-latest # Χρήση του τελευταίου Ubuntu περιβάλλοντος

        steps:
            # Βήμα 1: Checkout του κώδικα του αποθετηρίου
            - name: Checkout code
              uses: actions/checkout@v3

            # Βήμα 2: Εγκατάσταση του Hugo
            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: 'latest' # Εδώ μπορείς να επιλέξεις τη συγκεκριμένη έκδοση του Hugo ή την τελευταία

            # Βήμα 3: Build του site
            - name: Build Hugo site
              run: hugo --minify # Αυτό θα δημιουργήσει το περιεχόμενο στο φάκελο 'public'

            # Βήμα 4: Ανεβάστε το φάκελο public ως artifcat (προαιρετικό)
            - name: Upload public folder
              uses: actions/upload-artifact@v3
              with:
                  name: hugo-site
                  path: public
